// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxtwprezrzmrdzdexfpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dHdwcmV6cnptcmR6ZGV4ZnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTc0NjMsImV4cCI6MjA1OTg5MzQ2M30.ZgnsPyoYooh5tCrJpe-0MigFeJeeo9STYtlwDKYAAL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);